### ISSUE TITLE
Master doesn't compile with intel 11.1

### ISSUE THREAD

**Issue by markgoffin** [FluidityProject/fluidity#24]
My latest attempt to build using ifort 11.1 has produced the following errors:

```
Fields_Allocates.F90(2664): error #6780: A dummy argument with the INTENT(IN) attribute shall not appear in a variable definition context   [MESH]
      mesh%adj_lists%nnlist => nnlist
------^
Fields_Allocates.F90(2762): error #6780: A dummy argument with the INTENT(IN) attribute shall not appear in a variable definition context   [MESH]
      mesh%adj_lists%nelist => nelist
------^
Fields_Allocates.F90(2860): error #6780: A dummy argument with the INTENT(IN) attribute shall not appear in a variable definition context   [MESH]
      mesh%adj_lists%eelist => eelist
```

I believe this was changed in commit 9045e06179487ac in order to get intel 14 to play ball. Is there any reason we can't declare the mesh intent(inout)?
