### ISSUE TITLE
Fluidity does not build on Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by Patol75** [FluidityProject/fluidity#192]
Dear all,

Following the release of Ubuntu 18.04, it looks like Fluidity fails to build. The make instruction results in an ICE.
```
f951: internal compiler error: in is_illegal_recursion, at fortran/resolve.c:1576
signal_handlers.F90:32:29:

 function handle_sighup(signal)
                             1
Warning: Unused dummy argument ‘signal’ at (1) [-Wunused-dummy-argument]
signal_handlers.F90:46:29:

 function handle_sigint(signal)
                             1
Warning: Unused dummy argument ‘signal’ at (1) [-Wunused-dummy-argument]
signal_handlers.F90:59:30:

 function handle_sigterm(signal)
                              1
Warning: Unused dummy argument ‘signal’ at (1) [-Wunused-dummy-argument]
f951: Warning: Nonexistent include directory ‘include/’ [-Wmissing-include-dirs]
Exodusii_C_Interface.c: In function ‘c_read_ex_open’:
Exodusii_C_Interface.c:18:4: warning: implicit declaration of function ‘FLExit’ [-Wimplicit-function-declaration]
    FLExit("Fluidity was not configured with exodusII, reconfigure with '--with-exodusii'!");
    ^~~~~~
signal_handlers.F90:72:29:

 function handle_sigfpe(signal)
                             1
Warning: Unused dummy argument ‘signal’ at (1) [-Wunused-dummy-argument]
f951: Warning: Nonexistent include directory ‘include/’ [-Wmissing-include-dirs]
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from embed_python.c:36:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Makefile:123: recipe for target 'Futils.o' failed
make[1]: *** [Futils.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```
I have followed the following steps while trying to build Fluidity:

- Add the Fluidity ppa: ```sudo apt-add-repository ppa:fluidity-core/ppa```

- Install the Fluidity dev package: ```sudo apt install fluidity-dev```

- Download PETSc 3.8.4 from here: https://www.mcs.anl.gov/petsc/download/index.html

- Configure it with: ```./configure --with-debugging=0 --download-fblaslapack=1 --download-hypre=1 \
--download-blacs=1 --download-scalapack=1 --download-mumps=1 --download-ptscotch=1 \
--download-parmetis=1 --download-metis=1 --download-ml --download-suitesparse=1```

- Download Zoltan v3.83 from here: http://www.cs.sandia.gov/Zoltan/Zoltan_download.html

- Configure it with: ```../Zoltan_v3.83/configure -C --enable-f90interface --with-parmetis \
--with-parmetis-incdir=/home/thomas/Softwares/petsc-3.8.4/arch-linux2-c-opt/include \
--with-parmetis-libdir=/home/thomas/Softwares/petsc-3.8.4/arch-linux2-c-opt/lib \
--with-scotch --with-scotch-incdir=/home/thomas/Softwares/petsc-3.8.4/arch-linux2-c-opt/include \
--with-scotch-libdir=/home/thomas/Softwares/petsc-3.8.4/arch-linux2-c-opt/lib --with-gnumake
&& make everything -j
&& sudo make install```

- Configure Fluidity with: ```./configure --enable-2d-adaptivity --enable-debugging LDFLAGS="-L/usr/local/lib" \
FCFLAGS="-I/usr/local/include" CPPFLAGS="-I/usr/local/include" && \
sudo make clean && make -j && make -j fltools && sudo make -j install```

I have repeated those steps three times, with different compiler versions:

- gcc 6.4.0 & g++ 6.4.0 & gfortran 6.4.0,

- gcc 7.3.0 & g++ 7.3.0 & gfortran 7.3.0,

- gcc 8.0.1 & g++ 8.0.1 & gfortran 8.01,

and each time I ended up having the same ICE.

We discussed this with @stephankramer and early conclusions would be to submit the ICE to Launchpad. Any idea on a minimal piece of code to submit in order to reproduce the ICE ?

Thomas

**Comment by tmbgreaves** [comment]
Additionally - this is the second ICE we've had with bionic, the first being early-March as per logs at:

http://buildbot.ese.ic.ac.uk:8080/builders/bionic-standard/builds/4/steps/shell_2/logs/stdio

This then appeared to be resolved for three builds (March 3rd, 9th, 10th) before failing again with the current ICE, first seen March 17th.

**Comment by jrper** [comment]
For what it's worth, buildbot seems to be hitting an earlier ICE (with the same error) than the one @Patol75 reports. Playing around with the docker build, it's repeatably failing in Futils.F90 (and can be restricted to that file). Replacing 
```   character(len = file_extension_len(filename)) :: file_extension ```
with 
```   character(len = 4) :: file_extension ```
(or any other number) allows that particular file to compile, but doesn't really help with the one in signal_handlers.F90, nor in building a consistent minimal example.

**Comment by jrper** [comment]
Actually, I tell a lie. Making a more robust fix to the `file_extension` function in Futils.F90 allows a docker build.

**Comment by Patol75** [comment]
@jrper Can you provide a modified version of Futils.F90 so that I can test the compilation process on my system ?

**Comment by Patol75** [comment]
Thank you, I will be trying it and reporting tomorrow.

**Comment by Patol75** [comment]
I have swapped the Futils.F90 with the one provided by @jrper and succeeded in compiling Fluidity.  From what I see, you have only moved the function '''trim_file_extension_len''' upwards enough so that any call to this function (in '''file_extension_len''' or '''trim_file_extension''' in this case) happens after the function's actual code. There would be therefore some kind of ordering in the functions codes that has to be respected in order for gfortran to work properly.

I have run tests, see below the results.

- '''make unittest''' returns:
'''RESULTS
    Passes:   18146
    Warnings: 4; tests = ['./test_cg_interpolation', './test_conservative_interpolation_sa', './test_dg_interpolation_sa', './test_dg_interpolation']
    Failures: 10; tests = ['./test_matmul_t', './test_cg_interpolation', './test_conservative_interpolation_sa', './test_dg_interpolation_sa', './test_conservative_interpolation', './test_dg_interpolation']'''

- '''make test''' returns:
'''Summary of test problems with failures or warnings:
coarse-corner-limited.xml: PPPF
mmat-interpolation-2d-parallel.xml: F
square-convection-parallel-trivial.xml: PF

Passes:   1498
Failures: 3
Warnings: 0
cannot generate xml report without junit_xml module.'''

- '''make mediumtest''' is still running.

**Comment by jrper** [comment]
I'm glad it worked for you ,too. I was worried that docker bionic and native bionic had diverged somewhere. Regarding the workaround, my best guess was that some regression in 18.04 means that gfortran throws spurious recursion errors when dealing with public functions defined in the same module, but later in the code than the first use. I think it should be possible to build a minimal example on that basis, assuming an equivalent bug report hasn't already been submitted.

**Comment by drhodrid** [comment]
Hi James / Thomas,

Could one of you add these changes to a branch so that I can also test tomorrow?

Best wishes,

Rhod

**Comment by Patol75** [comment]
```
module futils
  implicit none
  private
  public :: file_extension_len, trim_file_extension_len, file_extension
contains
  pure function file_extension_len(filename) result(length)
    character(len = *), intent(in) :: filename
    integer :: length
    length = len(filename) - trim_file_extension_len(filename)
  end function file_extension_len
  function file_extension(filename)
    character(len = *), intent(in) :: filename
    character(len = file_extension_len(filename)) :: file_extension
    file_extension = filename(len(filename) - len(file_extension) + 1:)
  end function file_extension
  pure function trim_file_extension_len(filename) result(length)
    character(len = *), intent(in) :: filename
    integer :: length
    do length = len_trim(filename), 1, -1
      if(filename(length:length) == ".") then
        exit
      end if
    end do
    length = length - 1
  end function trim_file_extension_len
end module futils
```

Further comment on the ICE: the piece of code above alone fails:

```
thomas@tristan:~/Documents$ gfortran -c Futils.F90 
f951: internal compiler error: in is_illegal_recursion, at fortran/resolve.c:1579
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```

I may have figured out why. If you play around with the location of the three functions, you will notice that the above compilation passes ONLY if ```file_extension``` is defined last. However, the compilation passes WHATEVER the order of the three functions if the function result ```file_extension``` is declared as a character which length does not depend on any of the other two functions. Any thoughts ?

**Comment by jrper** [comment]
I think you've done most of the work to build a minimal example there. Getting rid of the last irrelevances would give something like

```fortran
module test
  implicit none
  public :: foo1, foo2, bar
contains
  pure function foo1()
    integer :: foo1
    foo1 = foo2()
  end function foo1
  function bar()
    character(len = foo1()) :: bar
    bar = ""
  end function bar
  pure function foo2()
    integer :: foo2
    foo2=3
  end function foo2
end module test
```

Which indeed fails with gcc 7.3.0 under bionic, but not with the same compiler installed via macports on mac OS X.

**Comment by jrper** [comment]
Regarding @tmbgreaves comment on #196 and an offline conversation with @stephankramer, is it worth setting up a buildbot queue for https://github.com/FluidityProject/fluidity/commit/6113ae6f9e1ce39ac1886cc236d46fb508806145 and seeing (i) does it build and (ii) what the test results look like there? I realise @Patol75 has a separate pull request concerning other issues which came up at #194.

**Comment by Patol75** [comment]
I guess it is always a good idea to go through buildbot. However, something worth mentioning here is that there might be an issue with buildbot (see #195). @Cmath2 is trying to build his branch for the new active detectors, however after building some tests fail with a SegFault in the Zoltan routines. This SegFault  occurs neither on @Cmath2 system nor on @drhodrid system. We are trying to figure out why, but it is unfortunately not obvious.
For what comes to #194, it is only fixing some missing int() calls in a few tests at the moment. We still have to look into the other tests, and as pointed by @jrmaddison, to understand why the assertion in Intersection_finder.F90 fails.

**Comment by jrper** [comment]
One more data point from my end: experimenting with your minimal test and docker, I also see failures with Debian Sid with gfortran 7.3.0-18 and fedora 28 with 8.0.1-0.20, meanwhile fedora 27 works with 7.3.1-5. I'm not sure if that helps diagnose whose problem this really is though.

**Comment by tmbgreaves** [comment]
@Patol75 - could you try running this through docker to reproduce the bug? That would (should..) be identical to the buildbot environment. Ie:

docker run --env PETSC_DIR=/usr/lib/petscdir/3.8.3 --env LD_LIBRARY_PATH=/usr/lib/petscdir/3.8.3/linux-gnu-c-opt/lib -it fluidity/buildbot:bionic-dev-build bash -il

.. and then check out and build from the interactive shell.

**Comment by Patol75** [comment]
I may have done something wrong, as the test does not run properly (Ubuntu 16.04.4).
I have installed docker-ce according to your comment in #195, run the above command, cloned fluidity master, changed branch, tried to build but had to first change the value of PETSC_DIR (it was set to /usr/lib/petscdir/3.6.3, directory that did not exist) and apply the bionic workaround from @jrper. Then, this is what I get:
```
root@63e856ceef6f:/fluidity/tests# ../tools/testharness.py -f detectors_parallel_adaptivity.xml
fluidity
--------------------------------------------------------------------------------
which fluidity: /fluidity/bin/fluidity
Revision: chris_particles:c0cb1d097dc1068c814c4b2fd144ba7bcc04813b (debugging)
Compile date: May 13 2018 23:32:09
OpenMP Support			no
Adaptivity support		yes
2D adaptivity support		yes
3D MBA support			no
CGAL support			no
MPI support			yes
Double precision		yes
NetCDF support			yes
Signal handling support		yes
Stream I/O support		yes
PETSc support			yes
Hypre support			yes
ARPACK support			no
Python support			yes
Numpy support			yes
VTK support			yes
Zoltan support			yes
Memory diagnostics		yes
FEMDEM support			no
Hyperlight support		no
libsupermesh support		no
--------------------------------------------------------------------------------
 
detectors_parallel_adaptivity: Running
detectors_parallel_adaptivity: Calling 'make input':
rm -f *.ele *.edge *.face *.node *.halo *.pvtu *.vtu *.detectors *.detectors.dat *.stat
rm -f gmsh.log gmsh_err.log
rm -f matrixdump matrixdump.info
rm -f fluidity.err-* fluidity.log-*
rm -rf detectors_[0-4]*
rm -rf *flredecomp*
cp src/square.msh .
detectors_parallel_adaptivity: mpiexec -n 2 ../../bin/flredecomp -i 1 -o 2 -v -l detectors detectors_flredecomp &&
mpiexec -n 2 ../../bin/fluidity -v2 -l detectors_flredecomp.flml
--------------------------------------------------------------------------
mpiexec has detected an attempt to run as root.
Running at root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

You can override this protection by adding the --allow-run-as-root
option to your cmd line. However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
detectors_parallel_adaptivity: Assigning variables:
detectors_parallel_adaptivity: Assigning solvers_converged = True
Variable computation raised an exception
--------------------------------------------------------------------------------
  1  from fluidity_tools import stat_parser
  2  s= stat_parser("detectors.stat")
  3  ElapsedTime=s["ElapsedTime"]["value"]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fluidity/regressiontest.py", line 291, in run_python
    exec self.code in varsdict
  File "<string>", line 2, in <module>
  File "/fluidity/tests/../tools/../python/fluidity_tools.py", line 326, in __init__
    statfile=file(filename, "r")
IOError: [Errno 2] No such file or directory: 'detectors.stat'
--------------------------------------------------------------------------------
detectors_parallel_adaptivity: failure.

Summary of test problems with failures or warnings:
detectors_parallel_adaptivity.xml: F

Passes:   0
Failures: 1
Warnings: 0
```
When I change branch locally and run the test, it passes.

**Comment by jrper** [comment]
One of the complications of docker is that under normal circumstances the default user it root. Try adding `-u fluidity` to Tim's call to set it to the normal user created in that container (i.e `docker run --env PETSC_DIR=/usr/lib/petscdir/3.8.3 --env LD_LIBRARY_PATH=/usr/lib/petscdir/3.8.3/linux-gnu-c-opt/lib -u fluidity -it fluidity/buildbot:bionic-dev-build bash -il`) or, for the same effect, running `su fluidity -l` inside your container bash session *before* you clone and build.

**Comment by Patol75** [comment]
Thanks James, did the trick.
I ended up with something more helpful (see below) than what we had previously with @Cmath2, will look into it tomorrow.
```
At line 1095 of file Zoltan_callbacks.F90
Fortran runtime error: Index '684297383' of dimension 1 of array 'rbuf' outside of expected range (52:1)
```
The line 1095 refers to the following call:
```
assemble/Zoltan_callbacks.F90:1095:          call pack_detector(detector, rbuf(rhead:rhead+zoltan_global_ndata_per_det-1+total_attributes), &
```
that involves this subroutine
```
femtools/Detector_Tools.F90:347:  subroutine pack_detector(detector,buff,ndims,nstages, attributes_buffer)
```

**Comment by tmbgreaves** [comment]
I think this is superseded by #204, which has been fixed, hence closing this issue. Please re-open if it's still a problem.
